### ISSUE TITLE
Prettier not working

### ISSUE THREAD

**Issue by RyProgrammer** [cse110-fa21-group8/cse110-fa21-group8#40]
**Describe the bug**

Problem with prettier working (shown in the screenshot)

**To Reproduce**
Follow the steps in the pipeline document up to before committing changes.

**Expected behavior**
Expected my code to look pretty.

**Screenshots**
![prettier-issues](https://user-images.githubusercontent.com/61443207/142564982-0bd09f90-a79c-4791-9fe6-0be7e6768b2f.JPG)

**Desktop (please complete the following information):**
 - OS (Windows -> Git Bash)

**Comment by tianyuezhang1997** [comment]
Sorry, Ryan. I couldn't reproduce this error, I even have tried to use a new computer, with (1) new VSCode (2) new git-bash (3) new nodejs & npm installed, even in that case, the prettier always work.

**Comment by tianyuezhang1997** [comment]
If your teammate also encountersed this issue, please contact me on Discord or Slack. We can schedule a one-on-one meeting for personal help tomorrow.
